FROM node:21-alpine

EXPOSE 8080
ARG APP_GITCOMMIT
ARG APP_VERSION
ARG NODE_ENV
ARG SESSION_SECRET
ARG AUTH_SECRET
ARG REDIRECT_INSECURE

ENV PORT=8080
ENV NODE_ENV="${NODE_ENV}"
ENV SESSION_SECRET="${SESSION_SECRET}"
ENV AUTH_SECRET="${AUTH_SECRET}"
ENV REDIRECT_INSECURE="${REDIRECT_INSECURE}"

# create app directory
WORKDIR /usr/src/app

# install app dependencies
COPY package*.json ./
RUN npm install
RUN printf "APP_GITCOMMIT=${APP_GITCOMMIT}\nAPP_VERSION=${APP_VERSION}\n" > .env

# Bundle app source
COPY . .

CMD [ "npm", "run", "start" ]
